// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/bwmarrin/discordgo"
	"github.com/techstart35/auto-reply-bot/context/user/app"
	user2 "github.com/techstart35/auto-reply-bot/context/user/gateway/persistence/mysql/user"
)

// Injectors from wire.go:

// アプリケーションサービスの作成
func InitApp(ctx context.Context, session *discordgo.Session) (*app.App, error) {
	repository, err := user2.NewRepository(ctx)
	if err != nil {
		return nil, err
	}
	appApp := app.NewApp(repository, session)
	return appApp, nil
}

// クエリの作成
func InitQuery(ctx context.Context) (*user2.Query, error) {
	query, err := user2.NewQuery(ctx)
	if err != nil {
		return nil, err
	}
	return query, nil
}
